# Generated by Django 5.1.6 on 2025-03-05 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_age_user_surname_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Введіть email з домену @gmail.com', regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
