# Generated by Django 5.1.6 on 2025-03-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
